/**
 * Regenerates the slug dropdown in the "Request Collective Content Change"
 * issue template based on the directories under content/_collective/.
 *
 * The companion workflow (.github/workflows/sync-collective-slugs.yaml)
 * runs this on push to main when content/_collective/** changes and commits
 * the result back. Running locally is fine too — the change is just to a
 * markdown-bracketed block in the YAML.
 *
 *   pnpm sync-collective-slugs            # rewrite if needed
 *   pnpm sync-collective-slugs --check    # exit non-zero if rewrite is needed
 *
 * The block to rewrite is bracketed by `# BEGIN AUTO-SLUGS` /
 * `# END AUTO-SLUGS` comments — never edit the slug field by hand or it
 * will be clobbered on the next push.
 */

import {
	existsSync,
	readdirSync,
	readFileSync,
	statSync,
	writeFileSync,
} from 'node:fs';
import {join} from 'node:path';

const ROOT = process.cwd();
const TEMPLATE_PATH = join(
	ROOT,
	'.github/ISSUE_TEMPLATE/collective-request.yml',
);
const COLLECTIVE_DIR = join(ROOT, 'content/_collective');

const BEGIN = '  # BEGIN AUTO-SLUGS';
const END = '  # END AUTO-SLUGS';

export function listSlugs(dir = COLLECTIVE_DIR): string[] {
	if (!existsSync(dir)) return [];
	return readdirSync(dir)
		.filter(name => !name.startsWith('.'))
		.filter(name => statSync(join(dir, name)).isDirectory())
		.sort();
}

export function buildSlugBlock(slugs: string[]): string {
	if (slugs.length === 0) {
		// No packs yet — render a free-text input that explains the situation.
		// The workflow guard catches typos either way; this just keeps the
		// template valid YAML when there's nothing to pick from.
		return [
			`${BEGIN} — no collective packs yet; this template is non-functional until at least one pack exists`,
			'  - type: input',
			'    id: slug',
			'    attributes:',
			'      label: Slug',
			'      description: No collective packs exist yet. Close this issue and use **Request Collective Content** to create one.',
			'      placeholder: ""',
			'    validations:',
			'      required: true',
			END,
		].join('\n');
	}
	return [
		`${BEGIN} — generated by sync-collective-slugs; do not edit by hand`,
		'  - type: dropdown',
		'    id: slug',
		'    attributes:',
		'      label: Slug',
		'      description: Pick the existing collective pack you want to change. The list is auto-generated from `content/_collective/` on `main`.',
		'      options:',
		...slugs.map(slug => `        - ${slug}`),
		'    validations:',
		'      required: true',
		END,
	].join('\n');
}

export function rewrite(template: string, slugs: string[]): string {
	const beginIdx = template.indexOf(BEGIN);
	const endIdx = template.indexOf(END);
	if (beginIdx < 0 || endIdx < 0) {
		throw new Error(
			`sync-collective-slugs: missing AUTO-SLUGS markers in ${TEMPLATE_PATH}`,
		);
	}
	const endLineEnd = template.indexOf('\n', endIdx);
	const before = template.slice(0, beginIdx);
	const after = endLineEnd >= 0 ? template.slice(endLineEnd) : '';
	const block = buildSlugBlock(slugs);
	return before + block + after;
}

/* c8 ignore start */
function main() {
	const checkOnly = process.argv.slice(2).includes('--check');

	const template = readFileSync(TEMPLATE_PATH, 'utf8');
	const next = rewrite(template, listSlugs());

	if (next === template) {
		console.log('sync-collective-slugs: no changes needed');
		return;
	}

	if (checkOnly) {
		console.error(
			'sync-collective-slugs: template is out of date — run `pnpm sync-collective-slugs` to update',
		);
		process.exit(1);
	}

	writeFileSync(TEMPLATE_PATH, next);
	console.log('sync-collective-slugs: updated template');
}

if (process.env.NODE_ENV !== 'test') {
	main();
}
/* c8 ignore stop */
