/**
 * Regenerates the member dropdown in the "Request Personal Pack" issue
 * template based on the slugs in `config/team.json`.
 *
 * The companion workflow (.github/workflows/sync-team-members.yaml) runs
 * this on push to main when `config/team.json` changes and commits the
 * result back. Running locally is fine — the change is just to a
 * markdown-bracketed block in the YAML.
 *
 *   pnpm sync-team-members           # rewrite if needed
 *   pnpm sync-team-members --check   # exit non-zero if rewrite is needed
 *
 * The block to rewrite is bracketed by `# BEGIN AUTO-MEMBERS` /
 * `# END AUTO-MEMBERS` comments — never edit the member field by hand or
 * it will be clobbered on the next push.
 *
 * Sister to sync-collective-slugs.ts; structure is intentionally parallel.
 */

import {existsSync, readFileSync, writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {loadTeam} from '../lib/team.js';

const ROOT = process.cwd();
const TEMPLATE_PATH = join(ROOT, '.github/ISSUE_TEMPLATE/personal-request.yml');
const TEAM_PATH = join(ROOT, 'config/team.json');

const BEGIN = '  # BEGIN AUTO-MEMBERS';
const END = '  # END AUTO-MEMBERS';

export function listMemberSlugs(teamPath: string = TEAM_PATH): string[] {
	if (!existsSync(teamPath)) return [];
	return loadTeam(teamPath)
		.map(m => m.slug)
		.sort();
}

export function buildMemberBlock(slugs: string[]): string {
	if (slugs.length === 0) {
		// No team yet — render a free-text input that explains the situation.
		// The orchestrator's member-known check catches typos either way; this
		// just keeps the template valid YAML when there's nothing to pick from.
		return [
			`${BEGIN} — no team members yet; this template is non-functional until config/team.json has at least one entry`,
			'  - type: input',
			'    id: member',
			'    attributes:',
			'      label: Member',
			'      description: No team members configured. Add one to `config/team.json` first.',
			'      placeholder: ""',
			'    validations:',
			'      required: true',
			END,
		].join('\n');
	}
	return [
		`${BEGIN} — generated by sync-team-members; do not edit by hand`,
		'  - type: dropdown',
		'    id: member',
		'    attributes:',
		'      label: Member',
		'      description: Pick the team member to generate a personal pack for. The list is auto-generated from `config/team.json` on `main`.',
		'      options:',
		...slugs.map(slug => `        - ${slug}`),
		'    validations:',
		'      required: true',
		END,
	].join('\n');
}

export function rewrite(template: string, slugs: string[]): string {
	const beginIdx = template.indexOf(BEGIN);
	const endIdx = template.indexOf(END);
	if (beginIdx < 0 || endIdx < 0) {
		throw new Error(
			`sync-team-members: missing AUTO-MEMBERS markers in ${TEMPLATE_PATH}`,
		);
	}
	const endLineEnd = template.indexOf('\n', endIdx);
	const before = template.slice(0, beginIdx);
	const after = endLineEnd >= 0 ? template.slice(endLineEnd) : '';
	const block = buildMemberBlock(slugs);
	return before + block + after;
}

/* c8 ignore start */
function main() {
	const checkOnly = process.argv.slice(2).includes('--check');

	const template = readFileSync(TEMPLATE_PATH, 'utf8');
	const next = rewrite(template, listMemberSlugs());

	if (next === template) {
		console.log('sync-team-members: no changes needed');
		return;
	}

	if (checkOnly) {
		console.error(
			'sync-team-members: template is out of date — run `pnpm sync-team-members` to update',
		);
		process.exit(1);
	}

	writeFileSync(TEMPLATE_PATH, next);
	console.log('sync-team-members: updated template');
}

if (process.env.NODE_ENV !== 'test') {
	main();
}
/* c8 ignore stop */
