/**
 * Regenerates the target dropdown in the "Request Product Content Change"
 * issue template based on what's on disk under `content/<product>/`. Lists
 * release packs as `<product>/<version>` and articles as
 * `<product>/<version>/articles/<slug>`, sorted newest-first by the parent
 * release's `meta.json.generated_at`.
 *
 * The companion workflow (.github/workflows/sync-change-targets.yaml) runs
 * this on push to main when `content/**` changes and commits the result
 * back if it changed.
 *
 *   pnpm sync-change-targets           # rewrite if needed
 *   pnpm sync-change-targets --check   # exit non-zero if rewrite is needed
 *
 * The block is bracketed by `# BEGIN AUTO-TARGETS` / `# END AUTO-TARGETS`.
 * Sister to sync-pack-options.ts; the two share the same content-discovery
 * logic. Kept separate so each template's sync runs independently and
 * failures don't cascade.
 *
 * Cap: top 50 targets — same reasoning as sync-pack-options. Beyond that
 * the dropdown becomes unusable.
 */

import {
	existsSync,
	readdirSync,
	readFileSync,
	statSync,
	writeFileSync,
} from 'node:fs';
import {join} from 'node:path';

const ROOT = process.cwd();
const TEMPLATE_PATH = join(ROOT, '.github/ISSUE_TEMPLATE/change-request.yml');
const CONTENT_DIR = join(ROOT, 'content');
const COLLECTIVE_DIR = '_collective';

const BEGIN = '  # BEGIN AUTO-TARGETS';
const END = '  # END AUTO-TARGETS';

const MAX_OPTIONS = 50;

export type TargetOption = {
	value: string;
	generatedAt: string;
};

function listDirs(path: string): string[] {
	if (!existsSync(path)) return [];
	return readdirSync(path).filter(entry => {
		try {
			return statSync(join(path, entry)).isDirectory();
		} catch {
			return false;
		}
	});
}

function readGeneratedAt(metaPath: string): string {
	try {
		const meta = JSON.parse(readFileSync(metaPath, 'utf8')) as Record<
			string,
			unknown
		>;
		return typeof meta.generated_at === 'string' ? meta.generated_at : '';
	} catch {
		return '';
	}
}

/**
 * Walks `contentDir` and returns one TargetOption per pack, plus one per
 * article. Collective packs are deliberately excluded — change-request is
 * for product release packs only; collective edits use collective-request.
 */
export function listTargetOptions(
	contentDir: string = CONTENT_DIR,
): TargetOption[] {
	const options: TargetOption[] = [];

	for (const top of listDirs(contentDir)) {
		// Skip collective and any other underscore-prefixed dirs.
		if (top === COLLECTIVE_DIR) continue;
		if (top.startsWith('_')) continue;

		const productDir = join(contentDir, top);
		for (const version of listDirs(productDir)) {
			const packDir = join(productDir, version);
			const generatedAt = readGeneratedAt(join(packDir, 'meta.json'));
			const packValue = `${top}/${version}`;
			options.push({value: packValue, generatedAt});

			// Articles use the parent pack's generatedAt so they sort together
			// with their pack — clearer in the dropdown than mixing them by
			// each article's own (often-empty) meta.
			const articlesDir = join(packDir, 'articles');
			for (const articleSlug of listDirs(articlesDir)) {
				options.push({
					value: `${packValue}/articles/${articleSlug}`,
					generatedAt,
				});
			}
		}
	}

	// Sort newest-first by generatedAt, then within the same generatedAt put
	// the pack itself before its articles (lexicographically the pack value
	// is a prefix of the article value, so an ascending tie-breaker on value
	// achieves that).
	options.sort((a, b) => {
		if (a.generatedAt && b.generatedAt) {
			const cmp = b.generatedAt.localeCompare(a.generatedAt);
			if (cmp !== 0) return cmp;
		} else if (a.generatedAt) {
			return -1;
		} else if (b.generatedAt) {
			return 1;
		}
		return a.value.localeCompare(b.value);
	});

	return options.slice(0, MAX_OPTIONS);
}

export function buildTargetOptionsBlock(options: TargetOption[]): string {
	if (options.length === 0) {
		return [
			`${BEGIN} — no product release packs on disk yet; this template is non-functional until at least one lands on main`,
			'  - type: input',
			'    id: target',
			'    attributes:',
			'      label: Target',
			'      description: No product release packs exist yet. Generate one by filing a "Request New Release Content" issue (release-request) first.',
			'      placeholder: ""',
			'    validations:',
			'      required: true',
			END,
		].join('\n');
	}
	return [
		`${BEGIN} — generated by sync-change-targets; do not edit by hand`,
		'  - type: dropdown',
		'    id: target',
		'    attributes:',
		'      label: Target',
		'      description: |',
		'        Pick what to edit. `<product>/<version>` targets the release pack itself (channels, meta, or a single file under it). `<product>/<version>/articles/<slug>` targets one article inside a pack. List is auto-generated from `content/` on `main`, sorted newest-first.',
		'      options:',
		...options.map(o => `        - ${o.value}`),
		'    validations:',
		'      required: true',
		END,
	].join('\n');
}

export function rewrite(template: string, options: TargetOption[]): string {
	const beginIdx = template.indexOf(BEGIN);
	const endIdx = template.indexOf(END);
	if (beginIdx < 0 || endIdx < 0) {
		throw new Error(
			`sync-change-targets: missing AUTO-TARGETS markers in ${TEMPLATE_PATH}`,
		);
	}
	const endLineEnd = template.indexOf('\n', endIdx);
	const before = template.slice(0, beginIdx);
	const after = endLineEnd >= 0 ? template.slice(endLineEnd) : '';
	const block = buildTargetOptionsBlock(options);
	return before + block + after;
}

/* c8 ignore start */
function main() {
	const checkOnly = process.argv.slice(2).includes('--check');

	const template = readFileSync(TEMPLATE_PATH, 'utf8');
	const next = rewrite(template, listTargetOptions());

	if (next === template) {
		console.log('sync-change-targets: no changes needed');
		return;
	}

	if (checkOnly) {
		console.error(
			'sync-change-targets: template is out of date — run `pnpm sync-change-targets` to update',
		);
		process.exit(1);
	}

	writeFileSync(TEMPLATE_PATH, next);
	console.log('sync-change-targets: updated template');
}

if (process.env.NODE_ENV !== 'test') {
	main();
}
/* c8 ignore stop */
