/**
 * Regenerates the base-pack dropdown in the "Request Personal Pack" issue
 * template based on what's on disk under `content/`. Lists product packs as
 * `<product>/<version>` and collective packs as `_collective/<slug>`, sorted
 * newest-first by `meta.json.generated_at` (falls back to alphabetical when
 * `generated_at` is missing).
 *
 * The companion workflow (.github/workflows/sync-pack-options.yaml) runs
 * this on push to main when `content/**` changes and commits the result
 * back if it changed.
 *
 *   pnpm sync-pack-options           # rewrite if needed
 *   pnpm sync-pack-options --check   # exit non-zero if rewrite is needed
 *
 * The block is bracketed by `# BEGIN AUTO-PACKS` / `# END AUTO-PACKS`. Sister
 * to sync-collective-slugs.ts and sync-team-members.ts; structure is
 * intentionally parallel.
 *
 * Cap: top 50 packs. Past that the dropdown becomes unusable, and an old
 * release that hasn't been picked in 50+ later releases probably isn't
 * worth a personal pack — the requester can fall back to editing the
 * issue body if they need an older one.
 */

import {
	existsSync,
	readdirSync,
	readFileSync,
	statSync,
	writeFileSync,
} from 'node:fs';
import {join} from 'node:path';

const ROOT = process.cwd();
const TEMPLATE_PATH = join(ROOT, '.github/ISSUE_TEMPLATE/personal-request.yml');
const CONTENT_DIR = join(ROOT, 'content');
const COLLECTIVE_DIR = '_collective';

const BEGIN = '  # BEGIN AUTO-PACKS';
const END = '  # END AUTO-PACKS';

const MAX_OPTIONS = 50;

export type PackOption = {
	value: string;
	generatedAt: string;
};

function listDirs(path: string): string[] {
	if (!existsSync(path)) return [];
	return readdirSync(path).filter(entry => {
		try {
			return statSync(join(path, entry)).isDirectory();
		} catch {
			return false;
		}
	});
}

function readGeneratedAt(metaPath: string): string {
	try {
		const meta = JSON.parse(readFileSync(metaPath, 'utf8')) as Record<
			string,
			unknown
		>;
		return typeof meta.generated_at === 'string' ? meta.generated_at : '';
	} catch {
		return '';
	}
}

/**
 * Walks `contentDir` and returns one PackOption per pack. Product packs are
 * listed as `<product>/<version>`; collective packs as `_collective/<slug>`.
 * Filters out leading-underscore directories at the top level except for
 * `_collective` itself (which is the sanctioned collective root).
 */
export function listPackOptions(
	contentDir: string = CONTENT_DIR,
): PackOption[] {
	const options: PackOption[] = [];

	for (const top of listDirs(contentDir)) {
		// `_collective` is special — its subdirs are individual collective packs.
		if (top === COLLECTIVE_DIR) {
			const collectiveRoot = join(contentDir, COLLECTIVE_DIR);
			for (const slug of listDirs(collectiveRoot)) {
				options.push({
					value: `${COLLECTIVE_DIR}/${slug}`,
					generatedAt: readGeneratedAt(join(collectiveRoot, slug, 'meta.json')),
				});
			}
			continue;
		}
		// Skip other underscore-prefixed dirs (`_test`, `_scratch`, etc.).
		if (top.startsWith('_')) continue;

		const productDir = join(contentDir, top);
		for (const version of listDirs(productDir)) {
			options.push({
				value: `${top}/${version}`,
				generatedAt: readGeneratedAt(join(productDir, version, 'meta.json')),
			});
		}
	}

	// Newest-first by generated_at; fall back to value-sorted (descending so
	// later semver versions float up) when generated_at is missing on both.
	options.sort((a, b) => {
		if (a.generatedAt && b.generatedAt) {
			return b.generatedAt.localeCompare(a.generatedAt);
		}
		if (a.generatedAt) return -1;
		if (b.generatedAt) return 1;
		return b.value.localeCompare(a.value);
	});

	return options.slice(0, MAX_OPTIONS);
}

export function buildPackOptionsBlock(options: PackOption[]): string {
	if (options.length === 0) {
		return [
			`${BEGIN} — no packs on disk yet; this template is non-functional until at least one pack lands on main`,
			'  - type: input',
			'    id: base_pack',
			'    attributes:',
			'      label: Base pack',
			'      description: No packs exist yet. Generate a release pack by filing a "Request New Release Content" issue (release-request), or a collective pack via the collective-request issue template, then come back here.',
			'      placeholder: ""',
			'    validations:',
			'      required: true',
			END,
		].join('\n');
	}
	return [
		`${BEGIN} — generated by sync-pack-options; do not edit by hand`,
		'  - type: dropdown',
		'    id: base_pack',
		'    attributes:',
		'      label: Base pack',
		'      description: |',
		'        Pick the existing pack to ground the personal-pack in. List is auto-generated from `content/` on `main`, sorted newest-first. `<product>/<version>` for release packs; `_collective/<slug>` for collective packs.',
		'      options:',
		...options.map(o => `        - ${o.value}`),
		'    validations:',
		'      required: true',
		END,
	].join('\n');
}

export function rewrite(template: string, options: PackOption[]): string {
	const beginIdx = template.indexOf(BEGIN);
	const endIdx = template.indexOf(END);
	if (beginIdx < 0 || endIdx < 0) {
		throw new Error(
			`sync-pack-options: missing AUTO-PACKS markers in ${TEMPLATE_PATH}`,
		);
	}
	const endLineEnd = template.indexOf('\n', endIdx);
	const before = template.slice(0, beginIdx);
	const after = endLineEnd >= 0 ? template.slice(endLineEnd) : '';
	const block = buildPackOptionsBlock(options);
	return before + block + after;
}

/* c8 ignore start */
function main() {
	const checkOnly = process.argv.slice(2).includes('--check');

	const template = readFileSync(TEMPLATE_PATH, 'utf8');
	const next = rewrite(template, listPackOptions());

	if (next === template) {
		console.log('sync-pack-options: no changes needed');
		return;
	}

	if (checkOnly) {
		console.error(
			'sync-pack-options: template is out of date — run `pnpm sync-pack-options` to update',
		);
		process.exit(1);
	}

	writeFileSync(TEMPLATE_PATH, next);
	console.log('sync-pack-options: updated template');
}

if (process.env.NODE_ENV !== 'test') {
	main();
}
/* c8 ignore stop */
