/**
 * Regenerates the product dropdown in the "Request New Release Content" issue
 * template from `config/products.json`. Issue forms can't read JSON at
 * runtime, so the dropdown is a static list we keep in sync with the config.
 *
 * The companion workflow (.github/workflows/sync-release-products.yaml) runs
 * this on push to main when `config/products.json` changes and opens a PR
 * with the result if it changed. Sister to sync-change-targets.ts.
 *
 *   pnpm sync-release-products           # rewrite if needed
 *   pnpm sync-release-products --check   # exit non-zero if rewrite is needed
 *
 * The block is bracketed by `# BEGIN AUTO-PRODUCTS` / `# END AUTO-PRODUCTS`.
 */

import {readFileSync, writeFileSync} from 'node:fs';
import {join} from 'node:path';

const ROOT = process.cwd();
const TEMPLATE_PATH = join(ROOT, '.github/ISSUE_TEMPLATE/release-request.yml');
const PRODUCTS_PATH = join(ROOT, 'config/products.json');

const BEGIN = '  # BEGIN AUTO-PRODUCTS';
const END = '  # END AUTO-PRODUCTS';

export type Product = {slug: string; repo: string};

export function loadProductSlugs(
	productsPath: string = PRODUCTS_PATH,
): string[] {
	const products = JSON.parse(readFileSync(productsPath, 'utf8')) as Product[];
	return products.map(p => p.slug);
}

export function buildProductOptionsBlock(slugs: string[]): string {
	if (slugs.length === 0) {
		return [
			`${BEGIN} — no products in config/products.json yet; this template is non-functional until at least one lands`,
			'  - type: input',
			'    id: product',
			'    attributes:',
			'      label: Product',
			'      description: No products are configured yet. Add one to `config/products.json` first.',
			'      placeholder: ""',
			'    validations:',
			'      required: true',
			END,
		].join('\n');
	}
	return [
		`${BEGIN} — generated by sync-release-products; do not edit by hand`,
		'  - type: dropdown',
		'    id: product',
		'    attributes:',
		'      label: Product',
		"      description: Which product's release to write about. List is auto-generated from `config/products.json` on `main`.",
		'      options:',
		...slugs.map(s => `        - ${s}`),
		'    validations:',
		'      required: true',
		END,
	].join('\n');
}

export function rewrite(template: string, slugs: string[]): string {
	const beginIdx = template.indexOf(BEGIN);
	const endIdx = template.indexOf(END);
	if (beginIdx < 0 || endIdx < 0) {
		throw new Error(
			`sync-release-products: missing AUTO-PRODUCTS markers in ${TEMPLATE_PATH}`,
		);
	}
	const endLineEnd = template.indexOf('\n', endIdx);
	const before = template.slice(0, beginIdx);
	const after = endLineEnd >= 0 ? template.slice(endLineEnd) : '';
	const block = buildProductOptionsBlock(slugs);
	return before + block + after;
}

/* c8 ignore start */
function main() {
	const checkOnly = process.argv.slice(2).includes('--check');

	const template = readFileSync(TEMPLATE_PATH, 'utf8');
	const next = rewrite(template, loadProductSlugs());

	if (next === template) {
		console.log('sync-release-products: no changes needed');
		return;
	}

	if (checkOnly) {
		console.error(
			'sync-release-products: template is out of date — run `pnpm sync-release-products` to update',
		);
		process.exit(1);
	}

	writeFileSync(TEMPLATE_PATH, next);
	console.log('sync-release-products: updated template');
}

if (process.env.NODE_ENV !== 'test') {
	main();
}
/* c8 ignore stop */
